repos:
- repo: local
  hooks:
  - id: ruff-lint-isort
    name: ruff-lint
    entry: ruff check --config ./pyproject.toml --fix .
    language: system
    types: [python]
    pass_filenames: false

  - id: ruff-format
    name: ruff-format
    entry: ruff format --config ./pyproject.toml .
    language: system
    types: [python]
    pass_filenames: false

      